### ISSUE TITLE
Animation sequence does not work?

### ISSUE THREAD

**Issue by e8johan** [nezticle/qml_movie_renderer#1]
Hi,

I have problems with property animations using this. For instance, changing the opacity from 0.0 to 1.0 to fade in an Image element results in the image element popping into view - there is no smooth transition.

The same applies to the angle of a 2.5D rotation effect.

I suspect that this has something to do with how the animation timeline is driven, but I know too little of the details to determine what the issue is. I've attached the qml giving me issues.

[intro.zip](https://github.com/nezticle/qml_movie_renderer/files/797483/intro.zip)

**Comment by nezticle** [comment]
I tested your example and it renders as it is supposed to with the movie renderer.  Your code doesn't do what you think it does.  You need to test your code in "live" mode before sending it to the renderer.  

You said that the "image element" pops in, but you don't have an opacity animation for the logo (just the text).  Also the text isn't visible because you are using the anchoring incorrectly.
